"""add pbp_completeness column

Revision ID: 129603aeb864
Revises: 9e8c250333f4
Create Date: 2026-09-15 21:30:19.682391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129603aeb864'
down_revision = '9e8c250333f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('pbp_completeness', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'pbp_completeness')
    # ### end Alembic commands ###
