"""add matches manifest table

Revision ID: 9e8c250333f4
Revises: 
Create Date: 2026-09-13 20:43:38.150019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8c250333f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('tournament_name', sa.String(), nullable=True),
    sa.Column('match_date', sa.Date(), nullable=True),
    sa.Column('player1', sa.String(), nullable=True),
    sa.Column('player2', sa.String(), nullable=True),
    sa.Column('surface', sa.String(), nullable=True),
    sa.Column('nbbet_match_id', sa.Integer(), nullable=True),
    sa.Column('championat_match_id', sa.Integer(), nullable=True),
    sa.Column('has_pbp', sa.Boolean(), nullable=True),
    sa.Column('pbp_s3_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
