"""add unique constraints on nbbet_match_id and championat_match_id

Revision ID: c467e1130ffc
Revises: 129603aeb864
Create Date: 2026-09-20 18:07:54.491964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c467e1130ffc'
down_revision = '129603aeb864'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_matches_championat_match_id', 'matches', ['championat_match_id'])
    op.create_unique_constraint('uq_matches_nbbet_match_id', 'matches', ['nbbet_match_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_matches_nbbet_match_id', 'matches', type_='unique')
    op.drop_constraint('uq_matches_championat_match_id', 'matches', type_='unique')
    # ### end Alembic commands ###
